auto_save: false
store_data: true
keep_prev: false

flags: null
labels: null
sort_labels: true
validate_label: null
show_label_text_field: true
sort_files_choices: ['SORT_BY_SHOW_TYPE_FN_AREA', 'SORT_BY_SHOW_TYPE_FN_max_AREA', 'SORT_BY_SHOW_TYPE_FP_AREA', 'SORT_BY_SHOW_TYPE_FP_max_AREA', 'reversed_sort']

#change_labelme_attr_with_gui_file_path: "D:/ws/projects/hobot_program/label_tool/refine_gt/bridge/change_labelme_attr_with_gui_hobot_example.py"
change_labelme_attr_with_gui_file_path: ""
# the image dir and save label dir, they can be used together, or only the save dir can be used
image_dir: null
save_labelme_dir: null
shape_editable_default: false

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  change_save_dir: Ctrl+R

  open_next: Right
  open_prev: Left

  zoom_in: Ctrl++
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  add_point: Ctrl+Shift+P
  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  edit_polygon: Ctrl+J
  edit_rectangle: Ctrl+K
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
  sort_files: Ctrl+Alt+S
